PLUGIN_NAME=				cert-warden-client
PLUGIN_VERSION=			0.1
PLUGIN_COMMENT=			Cert Warden Client
PLUGIN_MAINTAINER=	certwarden@gregtwallace.com
PLUGIN_WWW=					https://www.certwarden.com/

.include "../../Mk/plugins.mk"
